In [10]:

import pandas as pd # for data manipulation
import numpy as np # for data manipulation

from sklearn.model_selection import train_test_split # for splitting the data into train and test samples
from sklearn.metrics import classification_report # for model evaluation metrics
from sklearn import tree # for decision tree models

import plotly.express as px  # for data visualization
import plotly.graph_objects as go # for data visualization
import graphviz # for plotting decision tree graphs

In [12]:
# Set Pandas options to display more columns
pd.options.display.max_columns=50

# Read in the movie data csv
df=pd.read_csv('horror_movies_train.csv', encoding='utf-8')

#maybe filter out movies with no revenue or budget
#df = df[df['revenue'] != 0]
df.drop(df.tail(1).index,inplace=True)
df = df[['revenue','language','release_date','popularity','reviews','reviews_average','budget','runtime','genres']]

# REMOVE THIS LINE AFTER GENRES IS FIXED
del df['genres']

In [13]:
#switch language to numbers
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(encoder.fit_transform(df[['language']]).toarray())

#merge one-hot encoded columns back with original DataFrame
df = df.join(encoder_df)
del df['language']

In [14]:
# Python3 program two find number of
# days between two given dates
 
# A date has day 'd', month 'm' and year 'y'
 
 
class Date:
    def __init__(self, m, d, y):
        self.d = d
        self.m = m
        self.y = y
 
 
# To store number of days in all months from
# January to Dec.
monthDays = [31, 28, 31, 30, 31, 30,
             31, 31, 30, 31, 30, 31]
 
# This function counts number of leap years
# before the given date
 
 
def countLeapYears(d):
 
    years = d.y
 
    # Check if the current year needs to be considered
    # for the count of leap years or not
    if (d.m <= 2):
        years -= 1
 
    # An year is a leap year if it is a multiple of 4,
    # multiple of 400 and not a multiple of 100.
    return int(years / 4) - int(years / 100) + int(years / 400)
 
 
# This function returns number of days between two
# given dates
def getDifference(dt1, dt2):
 
    # COUNT TOTAL NUMBER OF DAYS BEFORE FIRST DATE 'dt1'
 
    # initialize count using years and day
    n1 = dt1.y * 365 + dt1.d
 
    # Add days for months in given date
    for i in range(0, dt1.m - 1):
        n1 += monthDays[i]
 
    # Since every leap year is of 366 days,
    # Add a day for every leap year
    n1 += countLeapYears(dt1)
 
    # SIMILARLY, COUNT TOTAL NUMBER OF DAYS BEFORE 'dt2'
 
    n2 = dt2.y * 365 + dt2.d
    for i in range(0, dt2.m - 1):
        n2 += monthDays[i]
    n2 += countLeapYears(dt2)
 
    # return difference between two counts
    return (n2 - n1)
 

# Declare a list that is to be converted into a column
date_number = []

# Driver program
for item in df['release_date']:
  dt1 = Date(1,1,1900)
  date = str(item)
  date = date.split("/")
  dt2 = Date(int(date[0]),int(date[1]),int(date[2]))
  date_number.append(float(getDifference(dt1,dt2)))

# Using 'Address' as the column name
# and equating it to the list
df['date_number'] = date_number
del df['release_date']

In [15]:
df.info()
print(df)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2264 entries, 0 to 2263
Data columns (total 56 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   revenue          2264 non-null   float64
 1   popularity       2264 non-null   float64
 2   reviews          2264 non-null   float64
 3   reviews_average  2264 non-null   float64
 4   budget           2264 non-null   float64
 5   runtime          2264 non-null   float64
 6   0                2264 non-null   float64
 7   1                2264 non-null   float64
 8   2                2264 non-null   float64
 9   3                2264 non-null   float64
 10  4                2264 non-null   float64
 11  5                2264 non-null   float64
 12  6                2264 non-null   float64
 13  7                2264 non-null   float64
 14  8                2264 non-null   float64
 15  9                2264 non-null   float64
 16  10               2264 non-null   float64
 17  11               2264 non-null   float64
 18  12               2264 non-null   float64
 19  13               2264 non-null   float64
 20  14               2264 non-null   float64
 21  15               2264 non-null   float64
 22  16               2264 non-null   float64
 23  17               2264 non-null   float64
 24  18               2264 non-null   float64
 25  19               2264 non-null   float64
 26  20               2264 non-null   float64
 27  21               2264 non-null   float64
 28  22               2264 non-null   float64
 29  23               2264 non-null   float64
 30  24               2264 non-null   float64
 31  25               2264 non-null   float64
 32  26               2264 non-null   float64
 33  27               2264 non-null   float64
 34  28               2264 non-null   float64
 35  29               2264 non-null   float64
 36  30               2264 non-null   float64
 37  31               2264 non-null   float64
 38  32               2264 non-null   float64
 39  33               2264 non-null   float64
 40  34               2264 non-null   float64
 41  35               2264 non-null   float64
 42  36               2264 non-null   float64
 43  37               2264 non-null   float64
 44  38               2264 non-null   float64
 45  39               2264 non-null   float64
 46  40               2264 non-null   float64
 47  41               2264 non-null   float64
 48  42               2264 non-null   float64
 49  43               2264 non-null   float64
 50  44               2264 non-null   float64
 51  45               2264 non-null   float64
 52  46               2264 non-null   float64
 53  47               2264 non-null   float64
 54  48               2264 non-null   float64
 55  date_number      2264 non-null   float64
dtypes: float64(56)
memory usage: 1.0 MB
         revenue  popularity  reviews  reviews_average      budget  runtime  \
0            0.0       2.231     23.0              5.4         0.0     70.0
1            0.0       0.600      0.0              0.0         0.0    101.0
2            0.0       0.811      5.0              4.4         0.0     71.0
3            0.0       0.946      3.0              4.7         0.0     80.0
4            0.0       2.724     10.0              4.3         0.0     76.0
...          ...         ...      ...              ...         ...      ...
2259  69623713.0      62.574   2447.0              6.4  15000000.0    107.0
2260    419559.0       1.132     28.0              5.2         0.0     95.0
2261   1023510.0      19.181   1057.0              6.0   6000000.0    111.0
2262  12017369.0       8.577    151.0              5.4  30000000.0    100.0
2263   5844868.0      15.342    686.0              7.0   6000000.0     98.0

        0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2259  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2260  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2262  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2263  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

       14   15   16   17   18  ...   25   26   27   28   29   30   31   32  \
0     0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2259  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2260  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2261  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2262  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2263  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

       33   34   35   36   37   38   39   40   41   42   43   44   45   46  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2259  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2260  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2262  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2263  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

       47   48  date_number
0     0.0  0.0      18900.0
1     0.0  0.0      20631.0
2     0.0  0.0      20878.0
3     0.0  0.0      20939.0
4     0.0  0.0      21062.0
...   ...  ...          ...
2259  0.0  0.0      38784.0
2260  0.0  0.0      40975.0
2261  0.0  0.0      43713.0
2262  0.0  0.0      36173.0
2263  0.0  0.0      31427.0

[2264 rows x 56 columns]

In [21]:
X = df[1:][:2263]
y = df[['revenue']][:2263]
np.ravel(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [23]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier
neural_network_pipe = make_pipeline(StandardScaler(), MLPClassifier(random_state=1, solver="sgd", hidden_layer_sizes=(8, 16,24))) # this "pipe" *first* scales the data, then trains the model
neural_network_pipe.fit(X_train, y_train)
neural_network_pipe.score(X_test, y_test)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

0.43109540636042404